
import { Question, QuestionType, Section } from './types';

export const EXAM_DATA: Section[] = [
  {
    id: 'mc_pronunciation',
    title: 'I. MULTIPLE CHOICE - Pronunciation',
    description: 'Which word has the underlined part pronounced differently from that of the others?',
    questions: [
      { id: 'p1', text: 'a)', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'comic'}, {id: 'B', text: 'money'}, {id: 'C', text: 'online'}, {id: 'D', text: 'product'}], correctAnswer: 'B' },
      { id: 'p2', text: 'b)', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'cycled'}, {id: 'B', text: 'listened'}, {id: 'C', text: 'happened'}, {id: 'D', text: 'decided'}], correctAnswer: 'D' },
      { id: 'p3', text: 'c)', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'sight'}, {id: 'B', text: 'mind'}, {id: 'C', text: 'birth'}, {id: 'D', text: 'slide'}], correctAnswer: 'C' },
      { id: 'p4', text: 'd)', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'senses'}, {id: 'B', text: 'feelings'}, {id: 'C', text: 'fingers'}, {id: 'D', text: 'colours'}], correctAnswer: 'A' },
      { id: 'p5', text: 'e)', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'ocean'}, {id: 'B', text: 'canyon'}, {id: 'C', text: 'country'}, {id: 'D', text: 'cave'}], correctAnswer: 'A' },
      { id: 'p6', text: 'f)', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'walked'}, {id: 'B', text: 'stopped'}, {id: 'C', text: 'learned'}, {id: 'D', text: 'surfed'}], correctAnswer: 'C' },
      { id: 'p7', text: 'g)', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'problem'}, {id: 'B', text: 'insect'}, {id: 'C', text: 'second'}, {id: 'D', text: 'desert'}], correctAnswer: 'A' },
      { id: 'p8', text: 'h)', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'trees'}, {id: 'B', text: 'stars'}, {id: 'C', text: 'sweets'}, {id: 'D', text: 'eggs'}], correctAnswer: 'C' },
      { id: 'p9', text: 'i)', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'adventure'}, {id: 'B', text: 'lasagne'}, {id: 'C', text: 'carry'}, {id: 'D', text: 'yoga'}], correctAnswer: 'C' },
      { id: 'p10', text: 'j)', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'pay'}, {id: 'B', text: 'cave'}, {id: 'C', text: 'valley'}, {id: 'D', text: 'sensation'}], correctAnswer: 'C' },
    ]
  },
  {
    id: 'mc_stress',
    title: 'I. MULTIPLE CHOICE - Stress Pattern',
    description: 'Which word has a different stress pattern from that of the others?',
    questions: [
      { id: 's1', text: 'a)', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'marine'}, {id: 'B', text: 'plastic'}, {id: 'C', text: 'resource'}, {id: 'D', text: 'concern'}], correctAnswer: 'B' },
      { id: 's2', text: 'b)', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'persuade'}, {id: 'B', text: 'provide'}, {id: 'C', text: 'convince'}, {id: 'D', text: 'worry'}], correctAnswer: 'D' },
      { id: 's3', text: 'c)', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'offer'}, {id: 'B', text: 'contact'}, {id: 'C', text: 'finish'}, {id: 'D', text: 'inspire'}], correctAnswer: 'D' },
      { id: 's4', text: 'd)', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'journey'}, {id: 'B', text: 'advance'}, {id: 'C', text: 'challenge'}, {id: 'D', text: 'island'}], correctAnswer: 'B' },
      { id: 's5', text: 'e)', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'wonderful'}, {id: 'B', text: 'different'}, {id: 'C', text: 'usual'}, {id: 'D', text: 'fantastic'}], correctAnswer: 'D' },
      { id: 's6', text: 'f)', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'bicycle'}, {id: 'B', text: 'alpaca'}, {id: 'C', text: 'video'}, {id: 'D', text: 'memory'}], correctAnswer: 'B' },
      { id: 's7', text: 'g)', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'apparent'}, {id: 'B', text: 'favorite'}, {id: 'C', text: 'popular'}, {id: 'D', text: 'media'}], correctAnswer: 'A' },
      { id: 's8', text: 'h)', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'playground'}, {id: 'B', text: 'smartphone'}, {id: 'C', text: 'bamboo'}, {id: 'D', text: 'handbag'}], correctAnswer: 'C' },
      { id: 's9', text: 'i)', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'surprise'}, {id: 'B', text: 'amaze'}, {id: 'C', text: 'inspire'}, {id: 'D', text: 'desert'}], correctAnswer: 'D' },
      { id: 's10', text: 'j)', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'kayaking'}, {id: 'B', text: 'rainforest'}, {id: 'C', text: 'opponent'}, {id: 'D', text: 'skydiving'}], correctAnswer: 'C' },
    ]
  },
  {
    id: 'mc_grammar_vocab',
    title: 'I. MULTIPLE CHOICE - Grammar & Vocabulary',
    questions: [
      { id: 'gv3', text: 'Speaker A: Oh, you have got new shoes. They look nice. How much are they?\nSpeaker B: They are ________ cheap, just $15.', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'obviously'}, {id: 'B', text: 'amazingly'}, {id: 'C', text: 'especially'}, {id: 'D', text: 'immediately'}], correctAnswer: 'B' },
      { id: 'gv4', text: 'Speaker A: Do you know the famous boyband One Direction?\nSpeaker B: Yes, my daughter was crazy ________ them. What a pity, they have split!', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'for'}, {id: 'B', text: 'with'}, {id: 'C', text: 'about'}, {id: 'D', text: 'to'}], correctAnswer: 'C' },
      { id: 'gv5', text: 'Speaker A: J.K. Rowling is my favorite author.\nSpeaker B: She is one of the ________ authors whose names are known worldwide.', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'best-sellings'}, {id: 'B', text: 'best-sellers'}, {id: 'C', text: 'best-seller'}, {id: 'D', text: 'best-selling'}], correctAnswer: 'D' },
      { id: 'gv6', text: 'Speaker A: Look at the picture. This used to be a craze for teenagers in previous decades.\nSpeaker B: Oh, it’s ________.', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'rock, paper, scissors'}, {id: 'B', text: 'bamboo jacks'}, {id: 'C', text: 'blind man’s buff'}, {id: 'D', text: 'tug of war'}], correctAnswer: 'D' },
      { id: 'gv7', text: 'Speaker A: You saw Peter? Was he in the room?\nSpeaker B: No, I ________ into the room and ________ out he ________ there.', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'went / found / was not'}, {id: 'B', text: 'went / founded / was not'}, {id: 'C', text: 'went / found / was'}, {id: 'D', text: 'went / founded / was'}], correctAnswer: 'A' },
      { id: 'gv8', text: 'Speaker A: Hello mom, is everything OK? What were the kids doing when I called?\nSpeaker B: Emma ________ the piano while Harry ________ a soccer match on TV.', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'was playing / is watching'}, {id: 'B', text: 'was playing / was watching'}, {id: 'C', text: 'was playing / were watching'}, {id: 'D', text: 'were playing / is watching'}], correctAnswer: 'B' },
      { id: 'gv9', text: 'Speaker A: What happened to you?\nSpeaker B: I ________ down when I ________ down the stairs.', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'fell / was walking'}, {id: 'B', text: 'fell / walked'}, {id: 'C', text: 'was falling / was walking'}, {id: 'D', text: 'was falling / walked'}], correctAnswer: 'A' },
      { id: 'gv10', text: 'Speaker A: Do you know where John lives now? India?\nSpeaker B: Well, he ________ in India, but now he lives in Germany.', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'didn’t use to live'}, {id: 'B', text: 'didn’t live'}, {id: 'C', text: 'used to living'}, {id: 'D', text: 'used to live'}], correctAnswer: 'D' },
      { id: 'gv11', text: 'Speaker A: Your new hairstyle looks terrific.\nSpeaker B: ________', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'I’m glad you like it.'}, {id: 'B', text: 'I can’t believe you said that.'}, {id: 'C', text: 'It’s none of your business.'}, {id: 'D', text: 'It’s not my style either.'}], correctAnswer: 'A' },
      { id: 'gv12', text: 'Speaker A: ________\nSpeaker B: The Minions.', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'What is your favorite type of film?'}, {id: 'B', text: 'Have you watched “The Minions”?'}, {id: 'C', text: 'How was the movie you watched last night?'}, {id: 'D', text: 'What cartoons do you like to watch?'}], correctAnswer: 'D' },
      { id: 'gv13', text: 'Speaker A: Brother, I miss our childhood.\nSpeaker B: The smell of the guavas always reminds me ________ our grandparents’ garden.', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'of'}, {id: 'B', text: 'with'}, {id: 'C', text: 'to'}, {id: 'D', text: 'at'}], correctAnswer: 'A' },
      { id: 'gv14', text: 'Speaker A: What should I have?\nSpeaker B: Sirloins, which have a moderate level of tenderness, give a slightly chewy ________.', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'flavor'}, {id: 'B', text: 'texture'}, {id: 'C', text: 'odor'}, {id: 'D', text: 'sensation'}], correctAnswer: 'B' },
      { id: 'gv15', text: 'Speaker A: Look at the streets. Rubbish is everywhere.\nSpeaker B: It is ________.', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'interesting'}, {id: 'B', text: 'disgusting'}, {id: 'C', text: 'fascinating'}, {id: 'D', text: 'exhausting'}], correctAnswer: 'B' },
      { id: 'gv16', text: 'Speaker A: Tell me something about this problem.\nSpeaker B: ________, which is a hearing problem, makes people hard to distinguish between musical pitches.', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'Color-blindness'}, {id: 'B', text: 'Tone-deafness'}, {id: 'C', text: 'Sensation loss'}, {id: 'D', text: 'Anosmia'}], correctAnswer: 'B' },
      { id: 'gv17', text: 'Speaker A: I ________ this movie 3 times.\nSpeaker B: The last time I ________ it was a month ago.', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'have watched / watched'}, {id: 'B', text: 'watched / have watched'}, {id: 'C', text: 'watched / watched'}, {id: 'D', text: 'have watched / have watched'}], correctAnswer: 'A' },
      { id: 'gv18', text: 'Speaker A: ________ you ever ________ The Great Wall of China?\nSpeaker B: Yes. I visited the Great Wall on my last trip to China.', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'Did / visit'}, {id: 'B', text: 'Will / visit'}, {id: 'C', text: 'Have / visited'}, {id: 'D', text: 'Are / visiting'}], correctAnswer: 'C' },
      { id: 'gv19', text: 'Speaker A: Who did you talk to? Was it James?\nSpeaker B: No, I haven’t talked to James since he ________ working at the company.', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'stops'}, {id: 'B', text: 'stopped'}, {id: 'C', text: 'has stopped'}, {id: 'D', text: 'has been stopping'}], correctAnswer: 'B' },
      { id: 'gv20', text: 'Speaker A: How long have you been living in London?\nSpeaker B: ________', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'since 6 months'}, {id: 'B', text: 'since 6 months ago'}, {id: 'C', text: 'for 6 months'}, {id: 'D', text: 'for 6 months ago'}], correctAnswer: 'C' },
      { id: 'gv21', text: 'Speaker A: We are having a big gathering this weekend.\nSpeaker B: ________', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'Nice to meet you.'}, {id: 'B', text: 'You will be great.'}, {id: 'C', text: 'It’s fantastic.'}, {id: 'D', text: 'Take your time.'}], correctAnswer: 'C' },
      { id: 'gv22', text: 'Speaker A: I finally got my driving license.\nSpeaker B: ________', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'Certainly.'}, {id: 'B', text: 'Sorry.'}, {id: 'C', text: 'Hello.'}, {id: 'D', text: 'Congratulations.'}], correctAnswer: 'D' },
      { id: 'gv23', text: 'Speaker A: When will you leave?\nSpeaker B: I will ________ earlier tomorrow to avoid traffic.', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'set off'}, {id: 'B', text: 'leave behind'}, {id: 'C', text: 'carry on'}, {id: 'D', text: 'dream of'}], correctAnswer: 'A' },
      { id: 'gv24', text: 'Speaker A: ________ off this 27-meter-high cliff into a lake is dangerous.\nSpeaker B: Yeah, but I love the thrill it brings.', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'Sailing'}, {id: 'B', text: 'Climbing'}, {id: 'C', text: 'Diving'}, {id: 'D', text: 'Surfing'}], correctAnswer: 'C' },
      { id: 'gv25', text: 'Speaker A: Are you going to travel alone on the trip to Europe?\nSpeaker B: Maybe, but I’m still looking for some ________.', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'family'}, {id: 'B', text: 'friend'}, {id: 'C', text: 'company'}, {id: 'D', text: 'partner'}], correctAnswer: 'C' },
      { id: 'gv26', text: 'Speaker A: What do you want to be when you grow up?\nSpeaker B: I want to ________ my dream to become a doctor.', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'live'}, {id: 'B', text: 'lean'}, {id: 'C', text: 'leave'}, {id: 'D', text: 'let'}], correctAnswer: 'A' },
      { id: 'gv27', text: 'Speaker A: Have you finished your homework?\nSpeaker B: Not ________.', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'just'}, {id: 'B', text: 'still'}, {id: 'C', text: 'yet'}, {id: 'D', text: 'already'}], correctAnswer: 'C' },
      { id: 'gv28', text: 'Speaker A: You look tired.\nSpeaker B: I ________ the report for 2 hours.', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'typed'}, {id: 'B', text: 'am typing'}, {id: 'C', text: 'have typed'}, {id: 'D', text: 'have been typing'}], correctAnswer: 'D' },
      { id: 'gv29', text: 'Speaker A: In the future, doctors might destroy cancer cells completely.\nSpeaker B: Hopefully, several studies have ________ that the new treatment can reduce the number of deaths.', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'showed'}, {id: 'B', text: 'shown'}, {id: 'C', text: 'been showed'}, {id: 'D', text: 'been shown'}], correctAnswer: 'B' },
      { id: 'gv30', text: 'Speaker A: Would you rather ________ with your family or friends?\nSpeaker B: Definitely my family. I love my family.', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'be'}, {id: 'B', text: 'to be'}, {id: 'C', text: 'being'}, {id: 'D', text: 'been'}], correctAnswer: 'A' },
      { id: 'gv31', text: 'Speaker A: ________\nSpeaker B: I have just got back from a summer camp in Canada.', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'Was the summer camp good?'}, {id: 'B', text: 'What have you been up to?'}, {id: 'C', text: 'Did you take a lot of pictures?'}, {id: 'D', text: 'What about you?'}], correctAnswer: 'B' },
      { id: 'gv32', text: 'Speaker A: I have got exams all week.\nSpeaker B: ________', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'That sounds great.'}, {id: 'B', text: 'Good to see you again.'}, {id: 'C', text: 'It was amazing.'}, {id: 'D', text: 'Good luck with that.'}], correctAnswer: 'D' },
      { id: 'gv33', text: 'Have you ever been on an adventure?', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'My favourite colour is green.'}, {id: 'B', text: 'It’s a rainy day today.'}, {id: 'C', text: 'Yes, I have been on a few adventurous trips, such as hiking and camping in the mountains.'}, {id: 'D', text: 'I have a pet cat. She is very adventurous.'}], correctAnswer: 'C' },
      { id: 'gv34', text: 'I ________ my keys. Can you help me look for them?', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'have lost'}, {id: 'B', text: 'lost'}, {id: 'C', text: 'was losing'}, {id: 'D', text: 'had lost'}], correctAnswer: 'A' },
      { id: 'gv35', text: 'We ________ our project yet.', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'haven’t finished'}, {id: 'B', text: 'had hadn’t finished'}, {id: 'C', text: 'didn’t finish'}, {id: 'D', text: 'were weren’t finishing'}], correctAnswer: 'A' },
      { id: 'gv36', text: 'We explored a ________ on our hike and it was amazing!', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'opponent'}, {id: 'B', text: 'adventure'}, {id: 'C', text: 'cave'}, {id: 'D', text: 'desert'}], correctAnswer: 'C' },
      { id: 'gv37', text: 'I went ________ in the river for the first time and it was so much fun!', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'inspiration'}, {id: 'B', text: 'sail'}, {id: 'C', text: 'skydiving'}, {id: 'D', text: 'Kayaking'}], correctAnswer: 'D' },
      { id: 'gv38', text: 'We’re going to ________ at a convenience store to grab some food.', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'leave behind'}, {id: 'B', text: 'stop off'}, {id: 'C', text: 'carry on'}, {id: 'D', text: 'inspire'}], correctAnswer: 'B' },
      { id: 'gv39', text: 'She ________ to Paris three times.', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'was'}, {id: 'B', text: 'has been'}, {id: 'C', text: 'were'}, {id: 'D', text: 'had been'}], correctAnswer: 'B' },
      { id: 'gv40', text: 'I love going on ________ with my friends.', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'adventure'}, {id: 'B', text: 'valley'}, {id: 'C', text: 'dune'}, {id: 'D', text: 'yacht'}], correctAnswer: 'A' },
      { id: 'gv41', text: 'Even though it’s tough, I’m going to ________ with my studies.', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'inspire'}, {id: 'B', text: 'stop off'}, {id: 'C', text: 'leave behind'}, {id: 'D', text: 'carry on'}], correctAnswer: 'D' },
      { id: 'gv42', text: 'They ________ each other for 10 years.', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'knew'}, {id: 'B', text: 'have known'}, {id: 'C', text: 'were knowing'}, {id: 'D', text: 'had known'}], correctAnswer: 'B' },
      { id: 'gv43', text: 'Speaker A: Don’t ________ your old clothes. It is a waste.\nSpeaker B: That’s right. You can choose some pieces of clothing and give them to charity.', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'throw away'}, {id: 'B', text: 'deal with'}, {id: 'C', text: 'run out of'}, {id: 'D', text: 'worried about'}], correctAnswer: 'A' },
      { id: 'gv44', text: 'Speaker A: What did you buy for your brother? AirPods?\nSpeaker B: I decided to buy Sony headphones ________ Apple AirPods.', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'because of'}, {id: 'B', text: 'instead of'}, {id: 'C', text: 'in spite of'}, {id: 'D', text: 'in charge of'}], correctAnswer: 'B' },
      { id: 'gv45', text: 'Speaker A: How much is the new iPhone?\nSpeaker B: Like most advanced and ________ products, it costs me a lot of money.', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'hi-tech'}, {id: 'B', text: 'second-hand'}, {id: 'C', text: 'home-made'}, {id: 'D', text: 'wind-up'}], correctAnswer: 'A' },
      { id: 'gv46', text: 'Speaker A: It was raining heavily.\nSpeaker B: Luckily, my backpack is ________, so my books didn’t get wet.', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'automatic'}, {id: 'B', text: 'waterproof'}, {id: 'C', text: 'solar'}, {id: 'D', text: 'ecological'}], correctAnswer: 'B' },
      { id: 'gv47', text: 'Speaker A: You can hardly keep your eyes open, ________?\nSpeaker B: I was sleepless last night.', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'do you'}, {id: 'B', text: 'don’t you'}, {id: 'C', text: 'can’t you'}, {id: 'D', text: 'can you'}], correctAnswer: 'D' },
      { id: 'gv48', text: 'Speaker A: Why don’t you join the party?\nSpeaker B: There are ________ people in the party. The loud music makes me feel dizzy.', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'too few'}, {id: 'B', text: 'too little'}, {id: 'C', text: 'too many'}, {id: 'D', text: 'too much'}], correctAnswer: 'C' },
      { id: 'gv49', text: 'Speaker A: My son keeps complaining about not being able to vote.\nSpeaker B: Oh yeah, he is ________ to vote.', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'not old enough'}, {id: 'B', text: 'old enough'}, {id: 'C', text: 'not enough old'}, {id: 'D', text: 'enough old'}], correctAnswer: 'A' },
      { id: 'gv50', text: 'Speaker A: Teacher, I need to submit my report today, ________?\nSpeaker B: Submit your report today, just as soon as you can.', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'do I'}, {id: 'B', text: 'don’t I'}, {id: 'C', text: 'needn’t I'}, {id: 'D', text: 'need I'}], correctAnswer: 'B' },
      { id: 'gv51', text: 'Speaker A: What do you think of these earrings?\nSpeaker B: ________. These are not too shiny.', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'I much prefer those ones'}, {id: 'B', text: 'They are real gold'}, {id: 'C', text: 'They cost $70'}, {id: 'D', text: 'I’m looking for some jewelry'}], correctAnswer: 'A' },
      { id: 'gv52', text: 'Speaker A: Which one is more suitable for mom?\nSpeaker B: ________. I think the crimson red lipstick will suit her.', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'Oh, it’s nice'}, {id: 'B', text: 'OK. Let’s see'}, {id: 'C', text: 'It is cheaper'}, {id: 'D', text: 'Well, you are right'}], correctAnswer: 'B' },
    ]
  },
  {
    id: 'signs',
    title: 'II. SIGN/NOTICE',
    questions: [
      { id: 'sn1', text: 'What does this sign mean?\n(Sign: Handrail required, No bare feet)', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'Bare feet are only allowed for children.'}, {id: 'B', text: 'Passengers should hold the handrail for safety.'}, {id: 'C', text: 'Wheeled vehicles can be put in 2 sides of the escalator.'}, {id: 'D', text: 'Children are able to use the escalator by themselves.'}], correctAnswer: 'B' },
      { id: 'sn2', text: 'What does this sign mean?\n(Sign: PEST CONTROL IN PROGRESS)', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'Only bugs and mice are in under control and cannot escape.'}, {id: 'B', text: 'Insects and animals are being kept for researching by scientists.'}, {id: 'C', text: 'Insects and mice are being caught by humans.'}, {id: 'D', text: 'The killing of harmful insects or animals is being performed.'}], correctAnswer: 'D' },
    ]
  },
  {
    id: 'word_formation',
    title: 'III. WORD FORMATION',
    questions: [
      { id: 'wf1', text: 'My life is as ________ busy as it always is. I really need a break to recharge my battery.', type: QuestionType.FILL_BLANK, note: 'CRAZE', correctAnswer: 'crazily' },
      { id: 'wf2', text: 'Hair stylists predict that wavy blonde hair will become ________ this summer.', type: QuestionType.FILL_BLANK, note: 'TREND', correctAnswer: 'trendy' },
      { id: 'wf3', text: 'She was dressed in ________ leggings and a sweatshirt.', type: QuestionType.FILL_BLANK, note: 'LEG', correctAnswer: 'leggings' },
      { id: 'wf4', text: 'My mom forgot to add salt to the soup, so it was ________.', type: QuestionType.FILL_BLANK, note: 'TASTE', correctAnswer: 'tasteless' },
      { id: 'wf5', text: 'Animal rights ________ believe that animals should be treated with respect and more rights than they currently do.', type: QuestionType.FILL_BLANK, note: 'ACT', correctAnswer: 'activists' },
      { id: 'wf6', text: 'Established in 2013, this is the first online ________ School with recognized certification in the UK.', type: QuestionType.FILL_BLANK, note: 'PERFUME', correctAnswer: 'perfumery' },
      { id: 'wf7', text: 'As an ________, he loves exploring untouched places on Earth.', type: QuestionType.FILL_BLANK, note: 'ADVENTURE', correctAnswer: 'adventurer' },
      { id: 'wf8', text: 'From here, you can look out to the ________ hills and mountains.', type: QuestionType.FILL_BLANK, note: 'DISTANCE', correctAnswer: 'distant' },
      { id: 'wf9', text: 'The book is worth reading. It is the most ________ book I\'ve ever read.', type: QuestionType.FILL_BLANK, note: 'FASCINATE', correctAnswer: 'fascinating' },
      { id: 'wf10', text: 'Natural disasters are ________ difficult to predict.', type: QuestionType.FILL_BLANK, note: 'EXTREME', correctAnswer: 'extremely' },
      { id: 'wf11', text: 'Their parents used to take them to the park to ________ every weekend.', type: QuestionType.FILL_BLANK, note: 'CYCLING', correctAnswer: 'cycle' },
      { id: 'wf12', text: 'Because of ________, the area of land covered with trees has declined considerably.', type: QuestionType.FILL_BLANK, note: 'FOREST', correctAnswer: 'deforestation' },
      { id: 'wf13', text: 'Please review and make any ________ to your essay before submitting it.', type: QuestionType.FILL_BLANK, note: 'CORRECT', correctAnswer: 'corrections' },
      { id: 'wf14', text: 'The motivational speaker\'s speech has ________ the audience to chase their dreams.', type: QuestionType.FILL_BLANK, note: 'INSPIRATION', correctAnswer: 'inspired' },
      { id: 'wf15', text: 'Tom is ________ and loves to try new things.', type: QuestionType.FILL_BLANK, note: 'ADVENTURE', correctAnswer: 'adventurous' },
      { id: 'wf16', text: 'Many students ________ in extracurricular activities like sports and music.', type: QuestionType.FILL_BLANK, note: 'PARTICIPANT', correctAnswer: 'participate' },
      { id: 'wf17', text: 'This job requires someone who is ________ in the field of finance.', type: QuestionType.FILL_BLANK, note: 'EXPERIENCE', correctAnswer: 'experienced' },
    ]
  },
  {
    id: 'reading_cloze_1',
    title: 'IV. READING - Multiple Choice Cloze Passage 1',
    description: 'One of the (1) ________ that cannot be overlooked in extreme sports...',
    questions: [
      { id: 'rc1_1', text: '(1)', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'bigger benefit'}, {id: 'B', text: 'bigger benefits'}, {id: 'C', text: 'biggest benefit'}, {id: 'D', text: 'biggest benefits'}], correctAnswer: 'D' },
      { id: 'rc1_2', text: '(2)', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'as'}, {id: 'B', text: 'like'}, {id: 'C', text: 'for'}, {id: 'D', text: 'to'}], correctAnswer: 'A' },
      { id: 'rc1_3', text: '(3)', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'who'}, {id: 'B', text: 'when'}, {id: 'C', text: 'where'}, {id: 'D', text: 'that'}], correctAnswer: 'D' },
      { id: 'rc1_4', text: '(4)', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'scenes'}, {id: 'B', text: 'senses'}, {id: 'C', text: 'scents'}, {id: 'D', text: 'sets'}], correctAnswer: 'B' },
      { id: 'rc1_5', text: '(5)', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'are never experienced'}, {id: 'B', text: 'will never experience'}, {id: 'C', text: 'have never experienced'}, {id: 'D', text: 'are never going to experience'}], correctAnswer: 'C' },
      { id: 'rc1_6', text: '(6)', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'become'}, {id: 'B', text: 'becomes'}, {id: 'C', text: 'became'}, {id: 'D', text: 'becoming'}], correctAnswer: 'A' },
    ]
  },
  {
    id: 'reading_cloze_2',
    title: 'IV. READING - Multiple Choice Cloze Passage 2',
    description: 'What is badminton? Badminton is a racket sport that is (7) ________ around the world...',
    questions: [
      { id: 'rc2_7', text: '(7)', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'played'}, {id: 'B', text: 'watched'}, {id: 'C', text: 'ignored'}, {id: 'D', text: 'disliked'}], correctAnswer: 'A' },
      { id: 'rc2_8', text: '(8)', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'been watched'}, {id: 'B', text: 'been disliked'}, {id: 'C', text: 'been ignored'}, {id: 'D', text: 'been played'}], correctAnswer: 'D' },
      { id: 'rc2_9', text: '(9)', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'clothes'}, {id: 'B', text: 'shape'}, {id: 'C', text: 'location'}, {id: 'D', text: 'mood'}], correctAnswer: 'B' },
      { id: 'rc2_10', text: '(10)', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'increase'}, {id: 'B', text: 'ignore'}, {id: 'C', text: 'reduce'}, {id: 'D', text: 'decrease'}], correctAnswer: 'A' },
      { id: 'rc2_11', text: '(11)', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'bat'}, {id: 'B', text: 'stick'}, {id: 'C', text: 'racket'}, {id: 'D', text: 'ball'}], correctAnswer: 'C' },
      { id: 'rc2_12', text: '(12)', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'courts'}, {id: 'B', text: 'rinks'}, {id: 'C', text: 'fields'}, {id: 'D', text: 'pools'}], correctAnswer: 'A' },
    ]
  },
  {
    id: 'comprehension_1',
    title: 'V. READING COMPREHENSION - Passage 1 (Gobi Desert)',
    questions: [
      { id: 'co1_1', text: 'The Gobi Desert is the world\'s largest desert.', type: QuestionType.TRUE_FALSE, correctAnswer: 'False' },
      { id: 'co1_2', text: 'There are more sand dunes in the Sahara than in the Gobi.', type: QuestionType.TRUE_FALSE, correctAnswer: 'True' },
      { id: 'co1_3', text: 'Some areas in the Gobi Desert have rainfall once every two or three years.', type: QuestionType.TRUE_FALSE, correctAnswer: 'True' },
      { id: 'co1_4', text: 'Thanks to the strong winds, it is safe to travel to the Gobi Desert in spring and fall.', type: QuestionType.TRUE_FALSE, correctAnswer: 'False' },
      { id: 'co1_5', text: 'What does the passage mainly discuss?', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'The Gobi Desert\'s natural features.'}, {id: 'B', text: 'The Gobi Desert\'s locals.'}, {id: 'C', text: 'The Gobi Desert\'s precipitation.'}, {id: 'D', text: 'The Gobi Desert\'s temperature.'}], correctAnswer: 'A' },
      { id: 'co1_6', text: 'What can they find in the Gobi\'s desert thanks to its low rainfall?', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'desert people'}, {id: 'B', text: 'glacier'}, {id: 'C', text: 'dinosaur\'s fossil'}, {id: 'D', text: 'salt lakes'}], correctAnswer: 'C' },
    ]
  },
  {
    id: 'comprehension_2',
    title: 'V. READING COMPREHENSION - Passage 2 (Ha Giang)',
    questions: [
      { id: 'co2_1', text: 'Ha Giang is a province in central Vietnam.', type: QuestionType.TRUE_FALSE, correctAnswer: 'False' },
      { id: 'co2_2', text: 'The Dong Van Karst Plateau in Ha Giang is a UNESCO World Heritage Site.', type: QuestionType.TRUE_FALSE, correctAnswer: 'True' },
      { id: 'co2_3', text: 'Ha Giang is home to only one ethnic minority group.', type: QuestionType.TRUE_FALSE, correctAnswer: 'False' },
      { id: 'co2_4', text: 'Ha Giang is an unpopular destination for travellers.', type: QuestionType.TRUE_FALSE, correctAnswer: 'False' },
      { id: 'co2_5', text: 'What is the Dong Van Karst Plateau in Ha Giang?', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'A popular beach destination'}, {id: 'B', text: 'A historic temple complex'}, {id: 'C', text: 'A wildlife sanctuary'}, {id: 'D', text: 'A UNESCO World Heritage Site'}], correctAnswer: 'D' },
      { id: 'co2_6', text: 'What is one popular activity to do in Ha Giang?', type: QuestionType.MULTIPLE_CHOICE, options: [{id: 'A', text: 'Trekking'}, {id: 'B', text: 'Scuba diving'}, {id: 'C', text: 'Shopping'}, {id: 'D', text: 'Skiing'}], correctAnswer: 'A' },
    ]
  },
  {
    id: 'transformation',
    title: 'VII. TRANSFORMATION',
    description: 'Rewrite the whole sentence completely.',
    questions: [
      { id: 'tr1', text: 'The last time I visited my grandparents was two months ago.', type: QuestionType.FILL_BLANK, correctAnswer: "I haven't visited my grandparents for two months." },
      { id: 'tr2', text: 'She hasn\'t eaten pizza for three days.', type: QuestionType.FILL_BLANK, correctAnswer: 'The last time she ate pizza was three days ago.' },
      { id: 'tr3', text: 'The last time we played tennis was in 2021.', type: QuestionType.FILL_BLANK, correctAnswer: "We haven't played tennis since 2021." },
      { id: 'tr4', text: 'There aren\'t any trees in front of my house anymore.', type: QuestionType.FILL_BLANK, correctAnswer: 'There used to be some trees in front of my house.' },
      { id: 'tr5', text: 'There is no longer a playground behind our school.', type: QuestionType.FILL_BLANK, correctAnswer: 'There used to be a playground behind our school.' },
      { id: 'tr6', text: 'There aren\'t any small shops on this street any longer.', type: QuestionType.FILL_BLANK, correctAnswer: 'There used to be some small shops on this street.' },
      { id: 'tr7', text: 'I am excited about visiting Ha Long Bay next month.', type: QuestionType.FILL_BLANK, correctAnswer: 'I am looking forward to visiting Ha Long Bay next month.' },
      { id: 'tr8', text: 'She is looking forward to meeting her cousins this weekend.', type: QuestionType.FILL_BLANK, correctAnswer: 'She is excited about meeting her cousins this weekend.' },
      { id: 'tr9', text: 'They are excited about starting their new school year.', type: QuestionType.FILL_BLANK, correctAnswer: 'They are looking forward to starting their new school year.' },
      { id: 'tr10', text: 'Many students join in the school festival every year.', type: QuestionType.FILL_BLANK, correctAnswer: 'Many students take part in the school festival every year.' },
      { id: 'tr11', text: 'My brother takes part in the football match.', type: QuestionType.FILL_BLANK, correctAnswer: 'My brother participates in the football match.' },
      { id: 'tr12', text: 'We joined in the environmental project last month.', type: QuestionType.FILL_BLANK, correctAnswer: 'We took part in the environmental project last month.' },
    ]
  }
];
